Repository wellwelwel/awesomeyou, pull requests merged in 2025-04, with the labels that each got.

#10 feat(raphamorim): add Rio
  static/maintainers/raphamorim/projects.json
Labels: projetos

#14 feat(josevalim): add Elixir and Devise
  static/maintainers/josevalim/projects.json
Labels: projetos

#8 feat(zenorocha): add Dracula Theme and React Email
  static/maintainers/zenorocha/projects.json
Labels: projetos

#11 feat(RafaelGSS): add Node.js
  static/maintainers/RafaelGSS/projects.json
Labels: projetos

#12 feat(lucianopf): add BrasilAPI and CEP Promise
  static/maintainers/lucianopf/projects.json
Labels: projetos

#23 feat(avelino): add Awesome Go
  static/maintainers/avelino/projects.json
Labels: projetos

#24 feat(aprendendofelipe): add tabnews.com.br
  static/maintainers/aprendendofelipe/projects.json
Labels: projetos

#25 feat(andrewsmedina): add Splinter and tsuru
  static/maintainers/andrewsmedina/projects.json
Labels: projetos

#22 feat(cirospaciari): add Bun and Socketify
  static/maintainers/cirospaciari/projects.json
Labels: projetos

#19 feat(filipedeschamps): add tabnews.com.br, Brasil API, CEP Promise, and Doom Fire Algorithm Playground
  static/maintainers/filipedeschamps/projects.json
Labels: projetos

#29 feat(marcosmarcolin): add phpsocket.io
  static/maintainers/marcosmarcolin/projects.json
Labels: Projetos

#34 docs: improve rules description
  docs/RULES.md
Labels: Documentação

#38 chore(rules): maintainers need at least one commit
  .github/workflows/ci_test.yml
  docs/RULES.md
  package.json
  tools/generate-maintainers-cache.mts
Labels: 📖 Documentação, 🔢 Métricas
