Repository wellwelwel/awesomeyou, pull requests merged in 2025-05, with the labels that each got.

#40 feat(jfoliveira): add Devopness - DevOps for AI Agents & Humans
  docs/RULES.md
  docs/SCORE.md
  schemas/projects.json
  src/components/Project.tsx
  src/configs/categories.ts
  src/pages/_dynamic/maintainer/_ld/faqs.ts
  src/pages/_dynamic/maintainer/_project.tsx
  src/pages/calculator.tsx
  src/pages/index.tsx
  src/theme/Footer/index.tsx
  static/maintainers/jfoliveira/projects.json
Labels: ➕ Projetos

#41 fix: use GitHub username when user has no name
  src/contexts/Maintainer.tsx
  src/pages/new/_form/_maintaner.tsx
  tools/generate-maintainers.mts
Labels: 👾 Bugs

#43 fix: revert "colaborador" to "contribuidor"
  docs/RULES.md
  docs/SCORE.md
  src/components/Project.tsx
  src/pages/_dynamic/maintainer/_ld/faqs.ts
  src/pages/_dynamic/maintainer/_project.tsx
  src/pages/calculator.tsx
  src/pages/index.tsx
  src/theme/Footer/index.tsx
Labels: 📖 Documentação, 🔍 SEO
